// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric_MType int32

const (
	Metric_GAUGE   Metric_MType = 0
	Metric_COUNTER Metric_MType = 1
)

// Enum value maps for Metric_MType.
var (
	Metric_MType_name = map[int32]string{
		0: "GAUGE",
		1: "COUNTER",
	}
	Metric_MType_value = map[string]int32{
		"GAUGE":   0,
		"COUNTER": 1,
	}
)

func (x Metric_MType) Enum() *Metric_MType {
	p := new(Metric_MType)
	*p = x
	return p
}

func (x Metric_MType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_MType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_metrics_proto_enumTypes[0].Descriptor()
}

func (Metric_MType) Type() protoreflect.EnumType {
	return &file_internal_proto_metrics_proto_enumTypes[0]
}

func (x Metric_MType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_MType.Descriptor instead.
func (Metric_MType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{0, 0}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mtype         Metric_MType           `protobuf:"varint,2,opt,name=mtype,proto3,enum=grpc.Metric_MType" json:"mtype,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_internal_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetMtype() Metric_MType {
	if x != nil {
		return x.Mtype
	}
	return Metric_GAUGE
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricRequest) Reset() {
	*x = UpdateMetricRequest{}
	mi := &file_internal_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricRequest) ProtoMessage() {}

func (x *UpdateMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMetricRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type UpdateMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricResponse) Reset() {
	*x = UpdateMetricResponse{}
	mi := &file_internal_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricResponse) ProtoMessage() {}

func (x *UpdateMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMetricResponse) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *UpdateMetricResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsRequest) Reset() {
	*x = UpdateMetricsRequest{}
	mi := &file_internal_proto_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsRequest) ProtoMessage() {}

func (x *UpdateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type UpdateMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsResponse) Reset() {
	*x = UpdateMetricsResponse{}
	mi := &file_internal_proto_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsResponse) ProtoMessage() {}

func (x *UpdateMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricRequest) Reset() {
	*x = GetMetricRequest{}
	mi := &file_internal_proto_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricRequest) ProtoMessage() {}

func (x *GetMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricRequest.ProtoReflect.Descriptor instead.
func (*GetMetricRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetricRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type GetMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricResponse) Reset() {
	*x = GetMetricResponse{}
	mi := &file_internal_proto_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricResponse) ProtoMessage() {}

func (x *GetMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricResponse.ProtoReflect.Descriptor instead.
func (*GetMetricResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *GetMetricResponse) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *GetMetricResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_proto_metrics_proto protoreflect.FileDescriptor

const file_internal_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/metrics.proto\x12\x04grpc\"\x8f\x01\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x05mtype\x18\x02 \x01(\x0e2\x12.grpc.Metric.MTypeR\x05mtype\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"\x1f\n" +
	"\x05MType\x12\t\n" +
	"\x05GAUGE\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x01\";\n" +
	"\x13UpdateMetricRequest\x12$\n" +
	"\x06metric\x18\x01 \x01(\v2\f.grpc.MetricR\x06metric\"R\n" +
	"\x14UpdateMetricResponse\x12$\n" +
	"\x06metric\x18\x01 \x01(\v2\f.grpc.MetricR\x06metric\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\x14UpdateMetricsRequest\x12&\n" +
	"\ametrics\x18\x01 \x03(\v2\f.grpc.MetricR\ametrics\"-\n" +
	"\x15UpdateMetricsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"8\n" +
	"\x10GetMetricRequest\x12$\n" +
	"\x06metric\x18\x01 \x01(\v2\f.grpc.MetricR\x06metric\"O\n" +
	"\x11GetMetricResponse\x12$\n" +
	"\x06metric\x18\x01 \x01(\v2\f.grpc.MetricR\x06metric\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xe0\x01\n" +
	"\x10MetricController\x12E\n" +
	"\fUpdateMetric\x12\x19.grpc.UpdateMetricRequest\x1a\x1a.grpc.UpdateMetricResponse\x12G\n" +
	"\rUpdateMetrics\x12\x19.grpc.UpdateMetricRequest\x1a\x1b.grpc.UpdateMetricsResponse\x12<\n" +
	"\tGetMetric\x12\x16.grpc.GetMetricRequest\x1a\x17.grpc.GetMetricResponseB\fZ\n" +
	"grpc/protob\x06proto3"

var (
	file_internal_proto_metrics_proto_rawDescOnce sync.Once
	file_internal_proto_metrics_proto_rawDescData []byte
)

func file_internal_proto_metrics_proto_rawDescGZIP() []byte {
	file_internal_proto_metrics_proto_rawDescOnce.Do(func() {
		file_internal_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_metrics_proto_rawDesc), len(file_internal_proto_metrics_proto_rawDesc)))
	})
	return file_internal_proto_metrics_proto_rawDescData
}

var file_internal_proto_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_proto_metrics_proto_goTypes = []any{
	(Metric_MType)(0),             // 0: grpc.Metric.MType
	(*Metric)(nil),                // 1: grpc.Metric
	(*UpdateMetricRequest)(nil),   // 2: grpc.UpdateMetricRequest
	(*UpdateMetricResponse)(nil),  // 3: grpc.UpdateMetricResponse
	(*UpdateMetricsRequest)(nil),  // 4: grpc.UpdateMetricsRequest
	(*UpdateMetricsResponse)(nil), // 5: grpc.UpdateMetricsResponse
	(*GetMetricRequest)(nil),      // 6: grpc.GetMetricRequest
	(*GetMetricResponse)(nil),     // 7: grpc.GetMetricResponse
}
var file_internal_proto_metrics_proto_depIdxs = []int32{
	0, // 0: grpc.Metric.mtype:type_name -> grpc.Metric.MType
	1, // 1: grpc.UpdateMetricRequest.metric:type_name -> grpc.Metric
	1, // 2: grpc.UpdateMetricResponse.metric:type_name -> grpc.Metric
	1, // 3: grpc.UpdateMetricsRequest.metrics:type_name -> grpc.Metric
	1, // 4: grpc.GetMetricRequest.metric:type_name -> grpc.Metric
	1, // 5: grpc.GetMetricResponse.metric:type_name -> grpc.Metric
	2, // 6: grpc.MetricController.UpdateMetric:input_type -> grpc.UpdateMetricRequest
	2, // 7: grpc.MetricController.UpdateMetrics:input_type -> grpc.UpdateMetricRequest
	6, // 8: grpc.MetricController.GetMetric:input_type -> grpc.GetMetricRequest
	3, // 9: grpc.MetricController.UpdateMetric:output_type -> grpc.UpdateMetricResponse
	5, // 10: grpc.MetricController.UpdateMetrics:output_type -> grpc.UpdateMetricsResponse
	7, // 11: grpc.MetricController.GetMetric:output_type -> grpc.GetMetricResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_proto_metrics_proto_init() }
func file_internal_proto_metrics_proto_init() {
	if File_internal_proto_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_metrics_proto_rawDesc), len(file_internal_proto_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_metrics_proto_goTypes,
		DependencyIndexes: file_internal_proto_metrics_proto_depIdxs,
		EnumInfos:         file_internal_proto_metrics_proto_enumTypes,
		MessageInfos:      file_internal_proto_metrics_proto_msgTypes,
	}.Build()
	File_internal_proto_metrics_proto = out.File
	file_internal_proto_metrics_proto_goTypes = nil
	file_internal_proto_metrics_proto_depIdxs = nil
}
